import "oaidl.idl";
import "ocidl.idl";
[
	uuid(d4866451-c006-4680-a2a7-a26e69c6d0aa),
	version(1.0)
]
interface learningRPC {
	// Take in a zero terminated string and echo it
	void Echo([in] handle_t h1,[in, string] unsigned char* pszString);
	void Shutdown([in] handle_t h1);
};

